name: Run tester updater

on:
  schedule:
    - cron: '0 0 */2 * *'  # Runs every 2 days at midnight (UTC)
  workflow_dispatch: # Allows manual triggering if needed

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grants write permission to the repository's contents
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check for changes and commit
      run: |
        echo "segundo" > test.txt
        
        # Configure Git user (GitHub Actions setup)
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        # Add modified or new files
        git add test.txt
        
        # Commit the changes only if there are any
        git diff --cached --quiet || git commit -m "Update test file from automation"
        
        # Push changes back to the repository
        echo "passo 6"
        git push origin main
