name: Run EPG updater

on:
  schedule:
    - cron: '0 0 */2 * *'  # Runs every 2 days at midnight (UTC)
  workflow_dispatch: # Allows manual triggering if needed

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up the environment (if needed)
      run: |
        sudo apt install xmltv -y

    - name: Run the existing script
      run: |
        # Make the script executable (if needed)
        chmod +x epgmerger.sh
        
        # Run the script to generate the output file
        ./epgmerger.sh

    - name: Check for changes and commit
      run: |
        ls -al
        chmod 644 epg.xmltv.gz
        echo "passo 1"
        # Configure Git user (GitHub Actions setup)
        echo "passo 2"
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        echo "passo 3"
        # Check if there are changes to commit
        pwd
        # git pull
        echo "passo 4"
        # Add modified or new files
        git add epg.xmltv.gz
        
        # Commit the changes only if there are any
        echo "passo 5"
        git diff --cached --quiet || git commit -m "Update epg.xmltv.gz file from automation"
        
        # Push changes back to the repository
        echo "passo 6"
        git push origin main
